### ISSUE TITLE
Label your inputs

### ISSUE THREAD

**Issue by oliverjam** [FAC-Sixteen/week4-team-pokedex#27]
Hey, just popping in with some accessibility advice :)

https://github.com/FAC-Sixteen/week4-team-pokedex/blob/39d14efe5ded310ea201a3bc7990be2cabb3bb54/index.html#L20

Inputs should have `<label> elements associated with them so users know what it's for. Placeholders aren't enough because:
1. They disappear as you type
1. They aren't necessarily read out as screenreaders

Generally placeholders are for examples of acceptable content, whereas labels describe what information the user is supposed to enter.

**Comment by dubhcait** [comment]
Thanks
