### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by Dalmano** [FAC-Sixteen/week4-team-pokedex#31]
the background image could remain centred when the screen size is increased/decreased

**Comment by tloth** [comment]
It's already positioned on the left side - could add white background to h1 "Rosmarin", or think of an other way round the issue of the legibility of green text on b/w background (when not on full screen)

![green on b/w](https://i.imgur.com/yP0g4mj.png)

**Comment by dubhcait** [comment]
Thanks
